version: '3.8'

services:
  app-sso:
    image: m-tracker-sso:latest
    container_name: mtracker-sso
    depends_on:
      - db
    restart: always
    env_file: ../app/env
    ports:
      - "8080:8080"
    networks:
      - mtracker-network
  db:
    image: postgres:latest
    container_name: psdb
    restart: always
    env_file: ./env
    ports:
      - "5432:5432"
    networks:
      - mtracker-network
    volumes:
      - ./pgdata:/pgdata

networks:
  mtracker-network:
    external: true