version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: psdb
    restart: always
    env_file: ./env
    ports:
      - "5432:5432"
    networks:
      - mtracker-network
    volumes:
      - ./pgdata:/pgdata

networks:
  mtracker-network:
    external: true