name: Build and test sso app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all tests and use remote contracts from bintray
        run: mvn -B clean verify
