name: Build and test sso app with current develop branch of contracts

on:
  pull_request:
    branches: [ develop ]

jobs:
  build_test_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout contracts
        uses: actions/checkout@v2
        with:
          repository: aredzo/demo-m-tracker-sso-spring-contracts
          path: contracts
          ref: "develop"
      - name: Build and install contracts
        run: mvn -B install
        working-directory: contracts

      - name: Checkout mtracker-sso
        uses: actions/checkout@v2
        with:
          path: sso
      - name: Test mtracker-sso with new contracts
        run: mvn -B clean verify -Dcontract.source=LOCAL
        working-directory: sso
